# Generated by Django 5.0.2 on 2025-02-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_fileupload_options_fileupload_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='file_uploads',
        ),
    ]
