# Generated by Django 5.0.2 on 2025-02-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_fileupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
