# Generated by Django 5.0.2 on 2025-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_fileupload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
